### ISSUE TITLE
description wording recommendations

### ISSUE THREAD

**Issue by Lukisong82** [chainbase-labs/manuscript-core#53]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/chainbase-labs/manuscript-core/issues), including closed ones.
- [X] I have searched for existing pull requests [search for existing pull requests](https://github.com/chainbase-labs/manuscript-core/pulls), including closed ones.

### Provide a description of requested docs changes

Any **_method_** (I recommend we use any "channel"): Different users are familiar with different forms of data access, we hope users can access data through various means, including but not limited to: SQL, DataFrames, HTTPS, gRPC, FTP, WebDAV, FUSE

Any **_data_** (I recommend we use any "format": Users should be able to access data in any format, such as: JSON, CSV, ORC, XML, XLSX, BLOB

**_Across_** any service (I recommend we delete "across") : Users’ expected data storage services also vary, we hope users can access, transfer, and control data in any service, such as: RPC, S3, IPFS, Azblob, HDFS, Google Drive, BigQuery, WebDAV, MySQL, PostgreSQL

**Comment by Liquidwe** [comment]
Hi @Lukisong82 

Suggestions are welcome~

“Method” encompasses various ways of data access and operations, such as SQL queries, DataFrame manipulations, HTTPS requests, and gRPC calls. These are technical means or interfaces for achieving data interaction and are concepts familiar to developers and data consumers.

“Channel” often refers to the path or medium of data transmission, such as network channels and communication protocols. It emphasizes the pathway of data transfer rather than how data access or operations are conducted, which can be misleading and suggest it only involves communication-level technologies.

“Any Data” refers not only to the format of data but also to its content and semantics. In data science and data engineering, data involves more than just format—it includes the processing and analysis of data content. This covers traditional big data storage (such as HDFS) and vector databases in AI, representing not just format differences but distinctions in data content and application methods across different scenarios.

“Any Format” might be misunderstood as merely supporting different file formats or data structure forms.

If there are more ideas, we can continue to discuss them further.
